version: '3.8'
services:
  katj:
    platform: linux/amd64
    image: katj
    container_name: katj
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always