
spring:
  boot:
    admin:
      server:
        base-path: /applications

  datasource:
    url: jdbc:mysql://jdbc:mysql://katj-db.clwqjlzrayle.ap-northeast-2.rds.amazonaws.com:3306/katj
    username: katj
    password: katj4
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database: h2
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080