spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://katj-db.clwqjlzrayle.ap-northeast-2.rds.amazonaws.com:3306/katj
    username: katj
    password: katj123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080

---
spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://katj-db-prod.clwqjlzrayle.ap-northeast-2.rds.amazonaws.com:3306/katj
    username: katj
    password: katj123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080