name: CI from sub feature branches

on:
  pull_request:
    branches:
      - feature-tony-dev_test
    types:
      - pull-request_review_comment

# env:
#  ACTIVE_PROFILE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  build-dev:
    #빌드 되는지 확인
    name: Build-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Link Check
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.git_hub_token }}
          reporter: github-pr-check # Change reporte

      # 환경변수 .env 파일 생성 및 write
      - name: Set .env for configuration
        run: |
          touch ./.env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}" >> ./.env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./.env
        #          echo "SPRING_PROFILES_ACTIVE=${{ env.ACTIVE_PROFILE }}" >> ./.env
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew clean build -x test

      #  deploy-dev:
      #    name: Deploy-dev
      #    runs-on: ubuntu-latest
      #    needs: build-dev
      #    environment: dev

  slack_noti:
    name: Slack_notification
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
        - name: action-slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            author_name: www-be
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
            if_mention: failure,cancelled
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
