name: Slack Notification
on:
  workflow_run:
    workflows: [build-dev]
    types:
      - completed
jobs:
  slack_noti:
    name: Slack_notification
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: dev 빌드 알림
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.